=== royllq/commons/src/main/resources/conf/dynabean.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--动态Bean定义 #PCDATA-->
<!ELEMENT InterFaceMapping ((PropertyIn, PropertyOut))>
<!ELEMENT PropertyOut ((COL*))>
<!ELEMENT PropertyIn ((COL*))>
<!ELEMENT COL ((#PCDATA,COL*))>
<!--
@attr  type         字段类型
-->
<!ATTLIST COL
	name ID #REQUIRED
	alias  CDATA #IMPLIED
	type (string|integer|datetime|dynaBean|javaBean|bytes|enums) "string"
	gtype (single|array|map |list) "single"
	isnull (true|false) "true"
    defaultValue CDATA #IMPLIED
    length CDATA #IMPLIED
    min  CDATA #IMPLIED
    max  CDATA #IMPLIED
    format CDATA #IMPLIED
    className CDATA #IMPLIED
    valueName   CDATA #IMPLIED
    strict   CDATA #IMPLIED
    convert CDATA #IMPLIED	
>

=== royllq/commons/src/test/resources/connector/TestJavaBean.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE InterFaceMapping PUBLIC  "-//andy.zhou//dynabean desc//ZH" 
"http://git.oschina.net/rjzjh/commons/raw/master/src/main/resources/conf/dynabean.dtd">
<InterFaceMapping>
	<PropertyIn>
		<COL name="single" type="javaBean"
			className="net.wicp.tams.commons.connector.beans.AddrInfo"
			defaultValue="{&quot;addr&quot;:&quot;娄山关路3号&quot;\,&quot;post&quot;:&quot;244100&quot;}">单个</COL>
		<COL name="array" type="javaBean"
			className="net.wicp.tams.commons.connector.beans.AddrInfo" gtype="array">
			数组
		</COL>
		<COL name="list" type="javaBean"
			className="net.wicp.tams.commons.connector.beans.AddrInfo" gtype="list">
			list
		</COL>
		<COL name="map" type="javaBean"
			className="net.wicp.tams.commons.connector.beans.AddrInfo" gtype="map">
			map
		</COL>
	</PropertyIn>
	<PropertyOut>
		<COL name="retMsg" type="string" convert="yesorno">返回信息</COL>
	</PropertyOut>
</InterFaceMapping>

=== royllq/commons/src/test/resources/connector/TestString.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE InterFaceMapping SYSTEM "D:\workspace\commons-util\src\test\resources\connector\dynabean.dtd">
<InterFaceMapping>
	<PropertyIn>
		<COL name="format" alias="format" type="string" format="^[0-9]{4}\\-[0-9]{1\,2}\\-[0-9]{1\,2}">格式注意，号也要转义</COL>
		<COL name="single" alias="single" type="string">简单单值</COL>
		<COL name="len" alias="len" type="string" length="5">限长单值</COL>
		<COL name="isnotnull" alias="isnotnull" type="string" isnull="false">不允许为空4444</COL>
		<COL name="defaultValue" alias="defaultValue" type="string" defaultValue="平安健康">带默认值</COL>
		<COL name="ary" alias="ary" type="string" gtype="array" length="10">数组</COL>
		<COL name="map" alias="map" type="string" gtype="map" length="10">Map</COL>
		<COL name="list" alias="list" type="string" gtype="list" length="10">List</COL>
	</PropertyIn>
	<PropertyOut>
		<COL name="retMsg" type="string" convert="yesorno">返回信息</COL>
	</PropertyOut>
</InterFaceMapping>

=== royllq/commons/src/test/resources/connector/TestByte.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE InterFaceMapping PUBLIC  "-//andy.zhou//dynabean desc//ZH" 
"http://git.oschina.net/rjzjh/commons/raw/master/src/main/resources/conf/dynabean.dtd">
<InterFaceMapping>
	<PropertyIn>
		<COL name="single" type="bytes" defaultValue="rjzjh">简单单值</COL>
		<COL name="ary" type="bytes" gtype="array">数组</COL>
		<COL name="map" type="bytes" gtype="map">Map</COL>
		<COL name="list" type="bytes" gtype="list">List</COL>
	</PropertyIn>
	<PropertyOut>
		<COL name="retMsg" type="string" convert="yesorno">返回信息</COL>
	</PropertyOut>
</InterFaceMapping>

=== royllq/commons/src/test/resources/connector/TestEnum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE InterFaceMapping SYSTEM "D:\workspace\commons-util\src\test\resources\connector\dynabean.dtd">
<InterFaceMapping>
	<PropertyIn>
		<COL name="single" type="enums" className="net.wicp.tams.commons.test.beans.SexEnum" defaultValue="F">简单单值</COL>
		<COL name="ary" type="enums" gtype="array" className="net.wicp.tams.commons.test.beans.SexEnum">数组</COL>
		<COL name="map" type="enums" gtype="map" className="net.wicp.tams.commons.test.beans.SexEnum">Map</COL>
		<COL name="list" type="enums" gtype="list" className="net.wicp.tams.commons.test.beans.SexEnum">List</COL>
	</PropertyIn>
	<PropertyOut>
		<COL name="retMsg" type="string" convert="yesorno">返回信息</COL>
	</PropertyOut>
</InterFaceMapping>

=== royllq/commons/src/test/resources/connector/TestDate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE InterFaceMapping PUBLIC  "-//andy.zhou//dynabean desc//ZH" 
"http://git.oschina.net/rjzjh/commons/raw/master/src/main/resources/conf/dynabean.dtd">
<InterFaceMapping>
	<PropertyIn>
		<COL name="datetime" type="datetime">时间类型</COL>
		<COL name="limit" type="datetime" min="2001-01-01" max="2002-01-01">时间跨度为2011整年</COL>
		<COL name="format" type="datetime" format="yyyy-MM-dd HH:mm:ss"  defaultValue="2013-01-01 10:10:10">时间格式</COL>


		<COL name="ary" type="datetime" gtype="array">数组</COL>
		<COL name="map" type="datetime" gtype="map">Map</COL>
		<COL name="list" type="datetime" gtype="list">List</COL>
	</PropertyIn>
	<PropertyOut>
		<COL name="retMsg" type="string" convert="yesorno">返回信息</COL>
	</PropertyOut>
</InterFaceMapping>
